name: PWBTestsGenerator health   

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [  macos-latest ]
        smalltalk:
          - Pharo64-8.0
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Run smalltalkCI self test
        run: smalltalkci -s ${{ matrix.smalltalk }} --self-test
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

